version: "3.9"  # optional since v1.27.0
services:
  web:
    container_name: tooele-crc
    build: 
      context: .
      target: dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env.development
  db:
    container_name: tooele-crc-mongo
    image: mongo
    restart: always
    ports: 
    - "27017:27017"
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tooele-crc
  test-db:
    container_name: tooele-crc-test-mongo
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tooele-crc
    
volumes:
  db-data:
