export { default as clientRouter } from './clientRouter'
export { default as userRouter } from './userRouter'
export { default as jobRouter } from './jobRouter'
export { default as purchaseRouter } from './purchaseRouter'
export { default as paymentRouter } from './paymentRouter'
export { default as noteRouter } from './noteRouter'
export { default as authRouter } from './authRouter'
